"""screening foundation: projects, sites, runs, scores, findings, events

Revision ID: 21e763a954ce
Revises: 
Create Date: 2026-07-11 17:47:35.933245
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '21e763a954ce'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.Enum('SOLAR', 'COMMUNITY_SOLAR', 'BATTERY_STORAGE', 'DATA_CENTER', 'EV_CHARGING', 'OTHER', name='projecttype', native_enum=False, length=32), nullable=False),
    sa.Column('target_capacity_mw', sa.Float(), nullable=True),
    sa.Column('minimum_acres', sa.Float(), nullable=False),
    sa.Column('target_state', sa.String(length=100), nullable=True),
    sa.Column('screening_criteria', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SCREENING', 'SCREENED', name='projectstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('acreage', sa.Float(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=200), nullable=False),
    sa.Column('road_distance_miles', sa.Float(), nullable=True),
    sa.Column('flood_overlap_percent', sa.Float(), nullable=True),
    sa.Column('wetland_overlap_percent', sa.Float(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('raw_input', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name_key', name='uq_candidate_site_project_name')
    )
    with op.batch_alter_table('candidate_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_sites_project_id'), ['project_id'], unique=False)

    op.create_table('screening_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SCREENING', 'DOCUMENT_ANALYSIS', 'NEEDS_REVIEW', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', name='screeningrunstatus', native_enum=False, length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_screening_run_project_idempotency_key')
    )
    with op.batch_alter_table('screening_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_runs_project_id'), ['project_id'], unique=False)

    op.create_table('risk_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('screening_run_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.Enum('DETERMINISTIC', 'DOCUMENT', 'HUMAN', name='findingsourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('category', sa.Enum('SITE_SUITABILITY', 'ENVIRONMENTAL', 'ACCESS', 'PERMITTING', 'DATA_COMPLETENESS', name='findingcategory', native_enum=False, length=32), nullable=False),
    sa.Column('group', sa.Enum('POSITIVE_SIGNAL', 'RISK', 'MISSING_INFORMATION', name='findinggroup', native_enum=False, length=32), nullable=False),
    sa.Column('rule', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'HIGH', 'FATAL', name='findingseverity', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'ESCALATED', name='reviewstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['candidate_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_findings_screening_run_id'), ['screening_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_findings_site_id'), ['site_id'], unique=False)

    op.create_table('site_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('screening_run_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('site_suitability_score', sa.Integer(), nullable=False),
    sa.Column('environmental_score', sa.Integer(), nullable=False),
    sa.Column('access_score', sa.Integer(), nullable=False),
    sa.Column('permitting_score', sa.Integer(), nullable=False),
    sa.Column('permitting_status', sa.Enum('NOT_ANALYZED', 'PENDING_DOCUMENT_REVIEW', 'ANALYZED', name='permittinganalysisstatus', native_enum=False, length=32), nullable=False),
    sa.Column('recommendation_status', sa.Enum('RECOMMENDED', 'RECOMMENDED_WITH_REVIEW', 'NEEDS_INVESTIGATION', 'HIGH_RISK', 'REJECT', name='recommendationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['candidate_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_run_id', 'site_id', name='uq_site_score_run_site')
    )
    with op.batch_alter_table('site_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_scores_screening_run_id'), ['screening_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_scores_site_id'), ['site_id'], unique=False)

    op.create_table('workflow_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('screening_run_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_events_screening_run_id'), ['screening_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_events_screening_run_id'))

    op.drop_table('workflow_events')
    with op.batch_alter_table('site_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_scores_site_id'))
        batch_op.drop_index(batch_op.f('ix_site_scores_screening_run_id'))

    op.drop_table('site_scores')
    with op.batch_alter_table('risk_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_findings_site_id'))
        batch_op.drop_index(batch_op.f('ix_risk_findings_screening_run_id'))

    op.drop_table('risk_findings')
    with op.batch_alter_table('screening_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_runs_project_id'))

    op.drop_table('screening_runs')
    with op.batch_alter_table('candidate_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_sites_project_id'))

    op.drop_table('candidate_sites')
    op.drop_table('projects')
    # ### end Alembic commands ###
