/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/demo/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Demo
         * @description Load the sample solar project: one project, five sites, one completed run.
         *
         *     Safe to call repeatedly. A second call returns the existing demo — 200, not
         *     201 — and creates nothing.
         */
        post: operations["seed_demo_api_demo_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Uploaded Document */
        get: operations["get_uploaded_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Analysis */
        get: operations["get_document_analysis_api_documents__document_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Uploaded Document */
        post: operations["analyze_uploaded_document_api_documents__document_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Review Site Finding
         * @description Approve, edit, reject, or escalate a finding.
         *
         *     Append-only: each decision writes a new ``reviews`` row and the extracted
         *     original is preserved, so an edit never destroys what the document actually
         *     said (spec §9.3).
         */
        patch: operations["review_site_finding_api_findings__finding_id__review_patch"];
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Newest first — the dashboard shows the most recent work at the top.
         */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Project Dashboard
         * @description Projects with their candidate count, top score, and risk rollups.
         *
         *     Declared before ``/{project_id}`` so that "dashboard" is not parsed as a
         *     project id.
         */
        get: operations["list_project_dashboard_api_projects_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/screenings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Screening
         * @description Screen every candidate site in the project.
         *
         *     Spec §18: a repeated request carrying the same ``Idempotency-Key`` returns
         *     the run that already exists — 200, not 201 — rather than screening twice.
         */
        post: operations["create_screening_api_projects__project_id__screenings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/screenings/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Screening
         * @description The project's most recent run, with its ranked results.
         *
         *     The results screen needs the project, the run, and the ranking together. 404
         *     means the project has not been screened yet — a normal state the UI shows as
         *     an empty state, not an error.
         */
        get: operations["get_latest_screening_api_projects__project_id__screenings_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sites
         * @description In import order, which is the order the user gave us.
         */
        get: operations["list_sites_api_projects__project_id__sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/sites/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Sites
         * @description Import candidate sites from a CSV.
         *
         *     Rows that fail validation are reported and not persisted; rows already
         *     imported are reported as duplicates and not persisted twice. The valid rows
         *     are written in one transaction, so a failure leaves the project as it was.
         */
        post: operations["import_sites_api_projects__project_id__sites_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenings/{screening_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Screening */
        get: operations["get_screening_api_screenings__screening_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenings/{screening_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Screening Events
         * @description The audit trail for a run, in the order the steps ran (spec §18).
         */
        get: operations["list_screening_events_api_screenings__screening_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Site
         * @description A site with its latest score, positive signals, risks, and missing information.
         */
        get: operations["get_site_api_sites__site_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site Brief */
        get: operations["get_site_brief_api_sites__site_id__brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Site Documents
         * @description Every permitting document uploaded for a site, oldest first.
         */
        get: operations["list_site_documents_api_sites__site_id__documents_get"];
        put?: never;
        /**
         * Upload Site Document
         * @description Upload and validate one zoning/permitting PDF for a candidate site.
         */
        post: operations["upload_site_document_api_sites__site_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Site Findings
         * @description Every finding for a site — deterministic and document-derived alike.
         *
         *     Evidence is eager-loaded: a document-derived claim is only meaningful with the
         *     excerpt it rests on, and the UI must never show one without the other.
         */
        get: operations["list_site_findings_api_sites__site_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report service liveness and whether the database is reachable.
         *
         *     A missing database does not fail the probe: the API is still up, and the
         *     frontend shell needs to render either way.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_sites_api_projects__project_id__sites_import_post */
        Body_import_sites_api_projects__project_id__sites_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_site_document_api_sites__site_id__documents_post */
        Body_upload_site_document_api_sites__site_id__documents_post: {
            /** File */
            file: string;
        };
        /**
         * BriefRankingEntry
         * @description One line of the candidate ranking, as it appears on the results screen.
         */
        BriefRankingEntry: {
            /** Is Selected Site */
            is_selected_site: boolean;
            /** Overall Score */
            overall_score: number;
            /** Rank */
            rank: number;
            /** Recommendation Status */
            recommendation_status: string;
            /** Site Id */
            site_id: string;
            /** Site Name */
            site_name: string;
        };
        /** CandidateSiteRead */
        CandidateSiteRead: {
            /** Acreage */
            acreage: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Flood Overlap Percent */
            flood_overlap_percent: number | null;
            /** Id */
            id: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Project Id */
            project_id: string;
            /** Road Distance Miles */
            road_distance_miles: number | null;
            /** Wetland Overlap Percent */
            wetland_overlap_percent: number | null;
        };
        /**
         * DemoSeedResponse
         * @description The seeded project and its completed screening run.
         */
        DemoSeedResponse: {
            /** Created */
            created: boolean;
            project: components["schemas"]["ProjectRead"];
            screening_run: components["schemas"]["ScreeningRunDetail"];
        };
        /** DocumentAnalysisResponse */
        DocumentAnalysisResponse: {
            document: components["schemas"]["DocumentResponse"];
            /** Findings */
            findings: components["schemas"]["RiskFindingRead"][];
            /** Summary */
            summary: string | null;
            /** Workflow Events */
            workflow_events: components["schemas"]["DocumentWorkflowEventResponse"][];
        };
        /**
         * DocumentProcessingStatus
         * @description Spec §15.6 — lifecycle of an uploaded permitting document.
         *
         *     CONTRACT CHANGE (integration). v1 drafted this as four members
         *     (``uploaded``/``processing``/``completed``/``failed``), but the
         *     document-analysis workflow needs to report which LangGraph stage a document
         *     is in, and it carried a second, parallel ``DocumentWorkflowStatus`` enum over
         *     the same column to say so. Two enums for one column is exactly the drift the
         *     contract exists to prevent, so the workflow's members are folded in here and
         *     the duplicate is gone. ``PROCESSING`` is retained as the coarse state for a
         *     document that is in flight but not in a named stage.
         * @enum {string}
         */
        DocumentProcessingStatus: "uploaded" | "processing" | "validating" | "extracting" | "retrieving" | "analyzing" | "needs_review" | "completed" | "partially_completed" | "failed";
        /** DocumentResponse */
        DocumentResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Message */
            error_message: string | null;
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /** Mime Type */
            mime_type: string;
            /** Page Count */
            page_count: number;
            processing_status: components["schemas"]["DocumentProcessingStatus"];
            /** Project Id */
            project_id: string;
            /** Site Id */
            site_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentWorkflowEventResponse
         * @description One LangGraph node's public audit record.
         *
         *     Named for the table it reads (``document_workflow_events``) so it is not
         *     confused with ``WorkflowEventRead``, which is a screening run's step. Carries
         *     the step, tool, status, structured output, and errors — never model reasoning
         *     (CLAUDE.md rule 6).
         */
        DocumentWorkflowEventResponse: {
            /** Analysis Request Id */
            analysis_request_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** Duration Ms */
            duration_ms: number;
            /** Error Message */
            error_message: string | null;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            }[];
            /** Id */
            id: string;
            /** Input Summary */
            input_summary: {
                [key: string]: unknown;
            };
            /** Node Name */
            node_name: string;
            /** Output Summary */
            output_summary: {
                [key: string]: unknown;
            };
            status: components["schemas"]["WorkflowEventStatus"];
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Excerpt */
            excerpt: string;
            /** Finding Id */
            finding_id: string;
            /** Id */
            id: string;
            /** Page Number */
            page_number: number;
            /** Section Name */
            section_name?: string | null;
        };
        /**
         * FindingCategory
         * @description Which screening dimension a finding belongs to.
         *
         *     The first four mirror the four scoring categories of spec §14.
         *     ``DATA_COMPLETENESS`` carries known-unknowns that carry no points.
         * @enum {string}
         */
        FindingCategory: "site_suitability" | "environmental" | "access" | "permitting" | "data_completeness";
        /**
         * FindingGroup
         * @description How a finding should be presented (spec §10.4).
         *
         *     Missing information is kept separate from confirmed risks: an absent input is
         *     not evidence of a problem, and the two must never be conflated in the UI.
         *
         *     ``REQUIREMENT`` was added at integration for document-derived permitting
         *     requirements. Filing them under ``RISK`` would assert that "a conditional-use
         *     permit is required" is a problem with the site, which it is not — it is an
         *     obligation, and it gets its own list on the site page.
         * @enum {string}
         */
        FindingGroup: "positive_signal" | "risk" | "missing_information" | "requirement";
        /**
         * FindingSeverity
         * @description Spec §13. A single ``FATAL`` finding forces a ``REJECT`` recommendation.
         * @enum {string}
         */
        FindingSeverity: "info" | "warning" | "high" | "fatal";
        /**
         * FindingSourceType
         * @description Spec §15.5 — how a finding was produced.
         * @enum {string}
         */
        FindingSourceType: "deterministic" | "document" | "human";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /** Environment */
            environment: string;
            /** Service */
            service: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** ImportSummary */
        ImportSummary: {
            /** Duplicate Rows */
            duplicate_rows: number;
            /** Imported Rows */
            imported_rows: number;
            /** Invalid Rows */
            invalid_rows: number;
            /** Total Rows */
            total_rows: number;
            /** Valid Rows */
            valid_rows: number;
        };
        /**
         * PermittingAnalysisStatus
         * @description Whether the permitting category rests on a real document.
         *
         *     Deterministic screening never analyzes a document, so a run on this branch
         *     always reports ``NOT_ANALYZED``. ``ANALYZED`` is reserved for the
         *     document-analysis branch, which owns the only code allowed to set it.
         * @enum {string}
         */
        PermittingAnalysisStatus: "not_analyzed" | "pending_document_review" | "analyzed";
        /** ProjectCreate */
        ProjectCreate: {
            /** Minimum Acres */
            minimum_acres: number;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            project_type: components["schemas"]["ProjectType"];
            screening_criteria?: components["schemas"]["ScreeningCriteria"];
            /** Target Capacity Mw */
            target_capacity_mw?: number | null;
            /** Target State */
            target_state?: string | null;
        };
        /**
         * ProjectDashboardItem
         * @description A project as the dashboard lists it.
         *
         *     The rollups are computed by the backend from the latest completed run. The
         *     dashboard, the results table, and the site page must agree on them, and they
         *     only can if one place derives them (spec §9.5).
         */
        ProjectDashboardItem: {
            /** Candidate Count */
            candidate_count: number;
            /** High Risk Finding Count */
            high_risk_finding_count: number;
            /** Latest Screening Run Id */
            latest_screening_run_id: string | null;
            project: components["schemas"]["ProjectRead"];
            /** Recommended Site Count */
            recommended_site_count: number;
            /** Top Score */
            top_score: number | null;
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Minimum Acres */
            minimum_acres: number;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            project_type: components["schemas"]["ProjectType"];
            screening_criteria: components["schemas"]["ScreeningCriteria"];
            status: components["schemas"]["ProjectStatus"];
            /** Target Capacity Mw */
            target_capacity_mw: number | null;
            /** Target State */
            target_state: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectStatus
         * @description Serialized as a plain string, which is all the v1 contract promises.
         * @enum {string}
         */
        ProjectStatus: "active" | "screening" | "screened";
        /**
         * ProjectType
         * @description Spec §10.2. ``COMMUNITY_SOLAR`` comes from the §16.1 request example.
         * @enum {string}
         */
        ProjectType: "solar" | "community_solar" | "battery_storage" | "data_center" | "ev_charging" | "other";
        /**
         * RecommendationStatus
         * @description Spec §8.1D / §14 — assigned deterministically from score and findings.
         * @enum {string}
         */
        RecommendationStatus: "recommended" | "recommended_with_review" | "needs_investigation" | "high_risk" | "reject";
        /**
         * RequirementCategory
         * @description The kind of permitting obligation a document-derived finding states.
         *
         *     Distinct from ``FindingCategory``, which says which of the four scoring
         *     dimensions a finding belongs to. A document finding is always
         *     ``FindingCategory.PERMITTING``; this says what sort of permitting item it is.
         * @enum {string}
         */
        RequirementCategory: "use_permission" | "setback" | "public_hearing" | "decommissioning" | "financial_security" | "environmental_study" | "traffic_study" | "application_requirement" | "other";
        /**
         * ReviewDecision
         * @description A reviewer's action on a finding. Maps onto ``ReviewStatus``.
         * @enum {string}
         */
        ReviewDecision: "approve" | "edit" | "reject" | "escalate";
        /** ReviewFindingRequest */
        ReviewFindingRequest: {
            decision: components["schemas"]["ReviewDecision"];
            /** Edited Description */
            edited_description?: string | null;
            /** Edited Title */
            edited_title?: string | null;
            /** Reviewer Note */
            reviewer_note?: string | null;
        };
        /**
         * ReviewStatus
         * @description State of a finding in the human-review loop (spec §8.1F).
         * @enum {string}
         */
        ReviewStatus: "pending" | "approved" | "edited" | "rejected" | "escalated";
        /**
         * RiskFindingRead
         * @description A persisted finding as returned by the API, whatever produced it.
         */
        RiskFindingRead: {
            /** Actual Value */
            actual_value: number | null;
            category: components["schemas"]["FindingCategory"];
            /** Confidence */
            confidence: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceResponse"][];
            group: components["schemas"]["FindingGroup"];
            /** Id */
            id: string;
            /** Original Description */
            original_description: string | null;
            /** Original Title */
            original_title: string | null;
            requirement_category: components["schemas"]["RequirementCategory"] | null;
            /** Requires Human Review */
            requires_human_review: boolean;
            review_status: components["schemas"]["ReviewStatus"];
            /** Rule */
            rule: string | null;
            /** Screening Run Id */
            screening_run_id: string | null;
            severity: components["schemas"]["FindingSeverity"];
            /** Site Id */
            site_id: string;
            source_type: components["schemas"]["FindingSourceType"];
            /** Threshold Value */
            threshold_value: number | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value */
            value: string | null;
        };
        /**
         * RowValidationError
         * @description One reason one CSV row was not imported.
         *
         *     ``row_number`` is the line number in the uploaded file, counting the header
         *     as line 1, so it matches what the user sees in a spreadsheet.
         */
        RowValidationError: {
            /** Field */
            field: string | null;
            /** Message */
            message: string;
            /** Row Number */
            row_number: number;
            /** Value */
            value?: string | null;
        };
        /**
         * ScoreBreakdownItem
         * @description One scoring rule, and what it awarded. Spec §9.5 — show every deduction.
         */
        ScoreBreakdownItem: {
            /** Actual Value */
            actual_value?: number | null;
            category: components["schemas"]["FindingCategory"];
            /** Explanation */
            explanation: string;
            /** Points Awarded */
            points_awarded: number;
            /** Points Possible */
            points_possible: number;
            /** Rule */
            rule: string;
            severity: components["schemas"]["FindingSeverity"];
            /** Threshold Value */
            threshold_value?: number | null;
        };
        /**
         * ScreeningCriteria
         * @description Thresholds a candidate site is screened against (spec §10.2 section B).
         *
         *     ``minimum_acres`` is not repeated here — it lives on the project itself, as
         *     in the contract's worked example.
         */
        ScreeningCriteria: {
            /**
             * Maximum Flood Overlap Percent
             * @default 5
             */
            maximum_flood_overlap_percent: number;
            /**
             * Maximum Road Distance Miles
             * @default 2
             */
            maximum_road_distance_miles: number;
            /**
             * Maximum Wetland Overlap Percent
             * @default 10
             */
            maximum_wetland_overlap_percent: number;
        };
        /**
         * ScreeningRunDetail
         * @description A run plus its ranked results, highest score first.
         *
         *     The project is embedded because every screen that shows a ranking also shows
         *     the criteria the ranking was produced against; sending them together means the
         *     UI cannot render a score next to a stale threshold.
         */
        ScreeningRunDetail: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: string;
            /** Idempotency Key */
            idempotency_key: string | null;
            project: components["schemas"]["ProjectRead"];
            /** Project Id */
            project_id: string;
            /** Results */
            results: components["schemas"]["SiteScreeningResult"][];
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["ScreeningRunStatus"];
        };
        /**
         * ScreeningRunStatus
         * @description Spec §18 — partial completion is a first-class outcome.
         * @enum {string}
         */
        ScreeningRunStatus: "queued" | "screening" | "document_analysis" | "needs_review" | "completed" | "partially_completed" | "failed";
        /**
         * SiteBriefRead
         * @description Everything the printable brief renders, in the order spec §8.1G lists it.
         */
        SiteBriefRead: {
            /** Candidate Ranking */
            candidate_ranking: components["schemas"]["BriefRankingEntry"][];
            /** Documents */
            documents: components["schemas"]["DocumentResponse"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Missing Information */
            missing_information: components["schemas"]["RiskFindingRead"][];
            /** Permitting Requirements */
            permitting_requirements: components["schemas"]["RiskFindingRead"][];
            /** Positive Signals */
            positive_signals: components["schemas"]["RiskFindingRead"][];
            project: components["schemas"]["ProjectRead"];
            /** Recommended Next Steps */
            recommended_next_steps: string[];
            /** Risks */
            risks: components["schemas"]["RiskFindingRead"][];
            score: components["schemas"]["SiteScoreRead"] | null;
            site: components["schemas"]["CandidateSiteRead"];
        };
        /**
         * SiteDetail
         * @description One site with its most recent screening result, if it has been screened.
         *
         *     ``score`` is ``None`` until a run has scored the site — an unscreened site is
         *     a normal state, not an error.
         *
         *     ``permitting_requirements`` are the document-derived findings for the site,
         *     each carrying its evidence and its review status. They are listed separately
         *     from ``risks`` because a permitting obligation is not a defect in the site,
         *     and from ``missing_information`` because it is not an unknown.
         */
        SiteDetail: {
            /** Documents */
            documents: components["schemas"]["DocumentResponse"][];
            /** Missing Information */
            missing_information: components["schemas"]["RiskFindingRead"][];
            /** Permitting Requirements */
            permitting_requirements: components["schemas"]["RiskFindingRead"][];
            /** Positive Signals */
            positive_signals: components["schemas"]["RiskFindingRead"][];
            project: components["schemas"]["ProjectRead"];
            /** Recommended Next Action */
            recommended_next_action: string;
            /** Risks */
            risks: components["schemas"]["RiskFindingRead"][];
            score: components["schemas"]["SiteScoreRead"] | null;
            site: components["schemas"]["CandidateSiteRead"];
        };
        /**
         * SiteImportResult
         * @description The response to a CSV import. Rows that fail validation are never persisted.
         */
        SiteImportResult: {
            /** Errors */
            errors: components["schemas"]["RowValidationError"][];
            /** Imported Sites */
            imported_sites: components["schemas"]["CandidateSiteRead"][];
            /** Project Id */
            project_id: string;
            summary: components["schemas"]["ImportSummary"];
        };
        /** SiteScoreRead */
        SiteScoreRead: {
            /** Access Score */
            access_score: number;
            /** Breakdown */
            breakdown: components["schemas"]["ScoreBreakdownItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Environmental Score */
            environmental_score: number;
            /** Explanation */
            explanation: string;
            /** Id */
            id: string;
            /** Overall Score */
            overall_score: number;
            /** Permitting Score */
            permitting_score: number;
            permitting_status: components["schemas"]["PermittingAnalysisStatus"];
            /** Rank */
            rank: number;
            recommendation_status: components["schemas"]["RecommendationStatus"];
            /** Screening Run Id */
            screening_run_id: string;
            /** Site Id */
            site_id: string;
            /** Site Suitability Score */
            site_suitability_score: number;
        };
        /**
         * SiteScreeningResult
         * @description One ranked site, with everything needed to explain its result.
         *
         *     The counts and the next action are computed here rather than in the UI. They
         *     are conclusions drawn from findings and a recommendation status, and the
         *     backend is the only place allowed to draw them (CLAUDE.md, spec §9.1).
         */
        SiteScreeningResult: {
            /** High Risk Finding Count */
            high_risk_finding_count: number;
            /** Missing Information */
            missing_information: components["schemas"]["RiskFindingRead"][];
            /** Permitting Requirements */
            permitting_requirements: components["schemas"]["RiskFindingRead"][];
            /** Positive Signals */
            positive_signals: components["schemas"]["RiskFindingRead"][];
            /** Recommended Next Action */
            recommended_next_action: string;
            /** Risks */
            risks: components["schemas"]["RiskFindingRead"][];
            score: components["schemas"]["SiteScoreRead"];
            site: components["schemas"]["CandidateSiteRead"];
            /** Warning Count */
            warning_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowEventRead */
        WorkflowEventRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: string;
            /** Input Summary */
            input_summary: string | null;
            /** Output Summary */
            output_summary: string | null;
            /** Screening Run Id */
            screening_run_id: string;
            /** Status */
            status: string;
            /** Step Name */
            step_name: string;
        };
        /**
         * WorkflowEventStatus
         * @enum {string}
         */
        WorkflowEventStatus: "started" | "completed" | "failed" | "skipped";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    seed_demo_api_demo_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSeedResponse"];
                };
            };
        };
    };
    get_uploaded_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_analysis_api_documents__document_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_uploaded_document_api_documents__document_id__analyze_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_site_finding_api_findings__finding_id__review_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewFindingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskFindingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_dashboard_api_projects_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDashboardItem"][];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_screening_api_projects__project_id__screenings_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_screening_api_projects__project_id__screenings_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_api_projects__project_id__sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateSiteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_sites_api_projects__project_id__sites_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_sites_api_projects__project_id__sites_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_api_screenings__screening_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_screening_events_api_screenings__screening_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_api_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_brief_api_sites__site_id__brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteBriefRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_site_documents_api_sites__site_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_site_document_api_sites__site_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_site_document_api_sites__site_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_site_findings_api_sites__site_id__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskFindingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
